[package]
name = "timesink-os"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "timesink-os"
path = "src/main.rs"
# This is necessary to rust-analyzer to stop from complaining about a missing
# test crate
test = false
doctest = false
bench = false

[dependencies]
